---
- name: Playbook para instalar la pila lamp
  hosts: bak
  become: yes

  tasks:

    - name: Descarga del codigo fuente de phpMyAdmin
      ansible.builtin.get_url:
        url: https://files.phpmyadmin.net/phpMyAdmin/5.2.0/phpMyAdmin-5.2.0-all-languages.zip
        dest: /tmp/

    - name: Descarga Unzip
      apt:
        name: unzip
        state: present

    - name: Descomprimir phpMyAdmin de /tmp
      unarchive:
        src:  /tmp/phpMyAdmin-5.2.0-all-languages.zip
        dest: /tmp/
        remote_src: yes
    
    - name: Eiliminacion de phpMyAdmin en /tmp
      file:
        path: /tmp/phpMyAdmin-5.2.0-all-languages.zip
        state: absent
    
    - name: Mover la carpeta de phpMyAdmin a /var/www/html/
      copy:
        src: /tmp/phpMyAdmin-5.2.0-all-languages/
        dest: /var/www/html/phpmyadmin
        remote_src: yes

    - name: Modificacion del usuario propietario del directorio /vars/www/html/phpmyadmin
      file: 
        path: /vars/www/html/phpmyadmin
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Instalamos el gestor de paquetes de Python3
      apt:
        name: python3-pip
        state: present

    - name: Instalamos el modulo de pymysql
      pip:
        name: pymysql
        state: present

    - name: Crear una base de datos
      mysql_db:
        name: "{{ DB_NAME }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Creamos un usuario para la Base de datos
      no_log: true
      mysql_user:
        name: "{{ DB_USER }}"
        password: "{{ DB_PASS }}"
        priv: "{{ DB_NAME }}.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock


    - name: Clonación de repositorio en /tmp/repo
      git:
        clone: true
        dest: /tmp/repo
        repo: https://github.com/josejuansanchez/iaw-practica-lamp.git

    - name: Borramos el archivo en caso de que exista
      ansible.builtin.file:
        path: /tmp/iaw-practica-lamp
        state: absent

    - name: Modificación del contenido de la base de datos
      ansible.builtin.replace:
        path: /tmp/repo/db/database.sql
        regexp: lamp_db
        replace: "{{ DB_NAME }}"

    - name: Añadimos la base de datos
      ansible.builtin.shell:
        mysql -u root < /tmp/repo/db/database.sql